dmw:
  railsEnvironment: development
  image:
    tag: develop@sha256:6dce3ea3487578d5841d3313d789ed9ceb735577e60aee41d71678e589676285

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    hosts:
      - host: 'dmw-test.framsburg.ch'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: ['dmw-test.framsburg.ch']
        secretName: 'dmw-test-framsburg-ch-tls'

  env:
    - name: SERVER_HOST_NAME
      value: 'dmw-test.framsburg.ch'

# podSecurityContext:
#  sysctls:
#    - name: fs.inotify.max_user_instances
#      value: "256"


