apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd-system
  data:
    - secretKey: oidc.authentik.clientSecret
      remoteRef:
        key: secret/data/framsburg/argocd/oidc
        property: client-secret
