apiVersion: v1
kind: Secret
metadata:
  name: oidc
  labels:
    app.kubernetes.io/part-of: argocd
data:
  oidc.authentik.clientSecret: dmF1bHQ6c2VjcmV0L2RhdGEvZnJhbXNidXJnL2FyZ29jZC9vaWRjI2NsaWVudC1zZWNyZXQ=
type: Opaque
