resources:
- templates/grafana-dashboard.yaml

helmCharts:
- name: jellyfin
  includeCRDs: false
  releaseName: jellyfin
  version: 9.5.3
  repo: https://k8s-at-home.com/charts
  valuesInline:
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        type: pvc
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        # existingClaim: jellyfin-media
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - worker
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: jellyfin2.framsburg.ch
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: jellyfin
        tls:
          - hosts: [jellyfin2.framsburg.ch]
            secretName: jellyfin2-framsburg-ch-tls
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1.5
        memory: 1024Mi
