apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: { .Release.Namespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://{{(include "loki.serviceName" .)}}.{{ .Release.Namespace }}.svc:{{ .Values.loki.service.port }}
      version: 1
