global:
  domainName: loki.framsburg.ch

loki-stack:
  fullnameOverride: loki-stack
  loki:
    fullnameOverride: loki
    serviceMonitor:
      enabled: true
  promtail:
    fullnameOverride: promtail
    serviceMonitor:
      enabled: true
