global:
  domainName: loki.framsburg.ch

loki:
  fullnameOverride: loki
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: '{{ .Values.global.domainName }}'
        paths: []
    tls:
      - hosts: ['{{ .Values.global.domainName }}']
        secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
