secrets-store-csi-driver:
  fullnameOverride: csi-secrets-store

  linux:
    image:
      repository: k8s.gcr.io/csi-secrets-store/driver
      tag: v1.1.1
    driver:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi

    registrarImage:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: v2.5.0
    registrar:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 100m
          memory: 100Mi

    livenessProbeImage:
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: v2.7.0
    livenessProbe:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 100m
          memory: 100Mi

  logVerbosity: 0
  logFormatJSON: false

  rbac:
    install: true

  syncSecret:
    enabled: true

  enableSecretRotation: false
  rotationPollInterval: "120s"
