resources:
- templates/disable-local-path.yaml
- templates/longhorn-middleware.yaml
- templates/longhorn-nfs-single.yaml
- templates/minio-secret.yaml

helmCharts:
- name: longhorn
  releaseName: longhorn
  version: 1.4.0
  repo: https://charts.longhorn.io
  valuesFile: values.yaml
