longhorn:
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    replicaAutoBalance: best-effort
    defaultReplicaCount: 2
    createDefaultDiskLabeledNodes: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-svc-longhorn-headers@kubernetescrd
    host: longhorn.framsburg.ch
    tls: true
    tlsSecret: longhorn-framsburg-ch-tls
  # longhornManager:
  #   nodeSelector:
  #     longhorn_enabled: "yes"
  # longhornDriver:
  #   nodeSelector:
  #     longhorn_enabled: "yes"

  resources:
    limits:
    cpu: 100m
    memory: 128Mi
    requests:
    cpu: 100m
    memory: 128Mi