persistence:
  defaultClassReplicaCount: 2
defaultSettings:
  concurrentAutomaticEngineUpgradePerNodeLimit: 1
  replicaAutoBalance: best-effort
  defaultReplicaCount: 2
  createDefaultDiskLabeledNodes: true
  backupTarget: 's3://k3sbackups@us-east-1/longhorn'
  backupTargetCredentialSecret: minio-secret
  defaultLonghornStaticStorageClass: longhorn
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-svc-longhorn-headers@kubernetescrd
  host: longhorn.framsburg.ch
  tls: true
  tlsSecret: longhorn-framsburg-ch-tls
resources:
  limits:
  cpu: 100m
  memory: 128Mi
  requests:
  cpu: 100m
  memory: 128Mi
