loki:
  fullnameOverride: loki
  serviceMonitor:
    enabled: true
  # persistence:
  #   enabled: true
  #   size: 20Gi
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    compactor:
      retention_enabled: true
  ingress:
    enabled: false
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: 'loki.framsburg.ch'
        paths: []
    tls:
      - hosts: ['loki.framsburg.ch']
        secretName: 'loki-framsburg-ch-tls'
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

