loki:
  # fullnameOverride: loki
  # persistence:
  #   enabled: true
  #   size: 20Gi
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  alerts:
    enabled: false
