apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: datasource-jaeger
data:
  jaeger.yaml: |
    apiVersion: 1
    datasources:
      - name: jaeger
        editable: false
        type: jaeger
        url: http://tracing-jaeger-query.tracing.svc:80

