---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
# spec:
#   strategy: production
#
#   storage:
#     type: elasticsearch

spec:
  strategy: allInOne
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - jaeger.framsburg.ch
    tls:
      - hosts:
          - jaeger.framsburg.ch
        secretName: jaeger-framsburg-ch-tls
    secretName: jaeger-framsburg-ch-tls
