global:
  domainName: filebrowser.framsburg.ch

filebrowser:
  controller:
    enabled: false
  env:
    TZ: Europe/Zurich

  config: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/config/database.db",
      "root": "/mnt/media"
    }
  
  service:
    main:
      ports:
        http:
          port: 8080

  persistence:
    audiobooks:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-audiobooks
      mountPath: /mnt/media/audiobooks

    movies:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies
      mountPath: /mnt/media/movies

    tv:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv
      mountPath: /mnt/media/tv

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
              service:
                name: filebrowser
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
