---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
  namespace: plex
  labels:
    app: ffmpeg
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: lscr.io/linuxserver/ffmpeg:latest
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: tv-uhd
              mountPath: /mnt/media/tv-uhd
            - name: tv-qrst
              mountPath: /mnt/media/tv-qrst
            - name: movies-uhd
              mountPath: /mnt/media/movies-uhd
      volumes:
        - name: tv-uhd
          persistentVolumeClaim:
            claimName: plex-tv-uhd
        - name: tv-qrst
          persistentVolumeClaim:
            claimName: plex-tv-qrst
        - name: movies-uhd
          persistentVolumeClaim:
            claimName: plex-movies-uhd
