vault-operator:
  crdAnnotations:
      "helm.sh/hook": crd-install

  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  monitoring:
    serviceMonitor:
      enabled: true
