longhorn:
  persistence:
    defaultClassReplicaCount: 3
  defaultSettings:
    replicaAutoBalance: best-effort
    defaultReplicaCount: 3
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-svc-longhorn-headers@kubernetescrd
    host: longhorn.framsburg.ch
    tls: true
    tlsSecret: longhorn-framsburg-ch-tls
