---
# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dmw
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.8

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 20Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: dmw-backup-store

  affinity:
    enablePodAntiAffinity: true

  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-dmw
spec:
  schedule: "0 0 12 * * *"
  backupOwnerReference: self
  cluster:
    name: dmw
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: dmw-backup-store
spec:
  retentionPolicy: "32d"
  configuration:
    destinationPath: s3://cnpg/backups
    endpointURL: https://minio2.framsburg.net:9000
    s3Credentials:
      accessKeyId:
        name: cnpg-minio-access
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-minio-access
        key: AWS_SECRET_ACCESS_KEY
    tags:
      backupRetentionPolicy: "expire"
    historyTags:
      backupRetentionPolicy: "keep"
