---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dmw
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dmw
  data:
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: secret/data/framsburg/dmw
        property: SENDGRID_API_KEY
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: secret/data/framsburg/dmw
        property: SECRET_KEY_BASE
