global:
  domainName: foundryvtt.framsburg.ch

foundryvtt:
  controller:
    enabled: false
  env:
    TZ: Europe/Zurich

    FOUNDRY_USERNAME:
      valueFrom:
        secretKeyRef:
          name: foundry-account-secret
          key: username
    FOUNDRY_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: foundry-account-secret
          key: password
    FOUNDRY_ADMIN_KEY:
      valueFrom:
        secretKeyRef:
          name: foundry-account-secret
          key: admin-key

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
