---
global:
  domainName: dex.framsburg.ch

dex:
  config:
    # Set it to a valid URL
    issuer: 'https://dex.framsburg.ch'

    # See https://dexidp.io/docs/storage/ for more options
    storage:
      type: memory

    # Enable at least one connector
    # See https://dexidp.io/docs/connectors/ for more options
    enablePasswordDB: true

  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

    hosts:
      - host: 'dex.framsburg.ch'
        paths:
          - path: /
            pathType: Prefix

    # tls:
    #   - secretName: 'dex-framsburg-ch-tls'
    #     hosts: ['dex.framsburg.ch']
