---
global:
  domainName: dex.framsburg.ch
dex:
  config:
    # Set it to a valid URL
    issuer: 'https://{{ .Values.global.domainName }}'

    # See https://dexidp.io/docs/storage/ for more options
    storage:
      type: memory

    # Enable at least one connector
    # See https://dexidp.io/docs/connectors/ for more options
    enablePasswordDB: true

  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

    hosts:
      - host: '{{ .Values.global.domainName }}'
        paths:
          - path: /

    tls:
      - hosts: ['{{ .Values.global.domainName }}']
        secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
