plex:
  persistence:
    config:
      enabled: true
  ingress:
    main:
      enabled: true
      hosts:
        - host: "plex.framsburg.ch"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: plex

