apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: sloth-slo-my-service
  namespace: rails-demo
  displayName: Requests Availability
spec:
  service: my-service
  description: "Common SLO based on availability for HTTP request responses."
  budgetingMethod: Occurrences
  objectives:
    - ratioMetrics:
        good:
          source: prometheus
          queryType: promql
          query: sum(rate(ruby_http_requests_total{code!~"(5..|429)"}[{{.window}}]))
        total:
          source: prometheus
          queryType: promql
          query: sum(rate(ruby_http_requests_total[{{.window}}]))
      target: 0.999
  timeWindows:
    - count: 30
      unit: Day
