{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails-demo.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rails-demo.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9394
      protocol: TCP
      name: metrics
  selector:
    {{- include "rails-demo.selectorLabels" . | nindent 4 }}
---
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
    {{- include "rails-demo.labels" . | nindent 4 }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
{{- end }}
  name: {{ include "rails-demo.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      {{- include "external-secrets.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
