apiVersion: v1
kind: Service
metadata:
  name: rails-demo-service
spec:
  type: ClusterIP
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
      name: http
