{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails-demo.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rails-demo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.config.serverPort }}
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "rails-demo.selectorLabels" . | nindent 4 }}
{{- end }}
