apiVersion: v1
kind: Service
metadata:
  name: rails-demo
spec:
  type: ClusterIP
  selector:
    app: rails-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
    - name: http-metrics
      port: 9394
      protocol: TCP
