apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: rails-demo-sla
  namespace: rails-demo
spec:
  service: "rails-demo"
  labels:
    owner: "myteam"
    repo: "myorg/myservice"
    tier: "2"
  slos:
    - name: "requests-availability"
      objective: 99.5
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        events:
          errorQuery: sum(rate(ruby_http_request_duration_seconds_count{code=~"(5..|429)"}[{{ .window }}]))
          totalQuery: sum(rate(ruby_http_request_duration_seconds_count[{{ .window }}]))
      alerting:
        pageAlert:
          disable: true
        ticketAlert:
          disable: true
