apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: sloth-slo-my-service
  namespace: monitoring-stack
spec:
  service: "rails-demo"
  labels:
    owner: "myteam"
    repo: "myorg/myservice"
    tier: "2"
  slos:
    - name: "requests-availability"
      objective: 99.9
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        events:
          errorQuery: sum(rate(ruby_http_request_duration_seconds_count{job="rails-demo-metrics",code=~"(5..|429)"}[{{.window}}]))
          totalQuery: sum(rate(ruby_http_request_duration_seconds_count{job="rails-demo-metrics"}[{{.window}}]))
      alerting:
        name: MyServiceHighErrorRate
        labels:
          category: "availability"
        annotations:
          summary: "High error rate on 'myservice' requests responses"

        ticketAlert:
          labels:
            severity: "slack"
            slack_channel: "#alerts"
