global:
  domainName: firefly.framsburg.ch

firefly:
  controller:
    enabled: true
  image:
    tag: "version-6.0.11"
  env:
    TZ: Europe/Zurich
    APP_URL: https://firefly.framsburg.ch

  importer:
    enabled: true
    image:
      tag: "version-1.2.2"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: performance
                  operator: In
                  values:
                    - medium
    specs:
      - accessToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTZjODhiNDk1M2EzMjMzNGM1ZmU5NjY4YjAxZGVjZGQzZTgwMTQ2YjZkOGM4ZDg3NzI3MjY5MWQyMzAxOGRjYzAwNzE5ZmQ4MWRjNjVkMjEiLCJpYXQiOjE2ODc5NTg1MDIuOTE2OTQ4LCJuYmYiOjE2ODc5NTg1MDIuOTE2OTUsImV4cCI6MTcxOTU4MDkwMi44OTc5NDIsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.izZtjy8UK06bFi8A7nvgKBgZlZRK-Aojq6ay0nj9vTHhEO2SEnwzsPXNoM_NWrwzoO8ddMTck9mLhu3cjjt5ckgJ6RDB_fWX3f0V236ow9tvk1x-R9dR1T8RSH6VTie6b6qm0nlaZMhVYoKDPclaBFcngeDhKY2IC45pH4jAr6jesP8XGnRRYYEXTUwE-qkSajtF88F7LH6ytTe7Fh0ey2XZPUVRIFldrNbndigjbBs_dw3Dg-VvoKaQkFS9wRwesRP_GopJEEmYdQtL0kwf4xbKlgGZ0_M9qrbd2mgXOApjZT4UcvwMH7FJq5b2eaHbLgxVglD3t7FhW3OEF9EY2VrfoxCsIKRcmdkuBXfBGvH1bMVBNSYVJao2khKnHyqRHa0994gQF79pzcMOi7aRjeWq42sWzRrFtDxcexvWTIF-gPSvmJFgfcCtnkBVUUj79vqKJj13g17DrpLE0DMIf5CxQY2wVUwudGmBJWwmoDxQW5d1mvu0F6R40Z_GHuLCYDEQkG4-k-Q9uP-k2s4fjVPBH9flSvgUkUZzt-rtzed3JvusL1WjD7X6yEHiTrXDb2bqaFsZ5ww5D1aTdxjDlKKvkxSUQNlV5ObOtsiXrY_bTA0MgYf48KFO3vaXGlFi9VUYm-4XqymFOnLmZ14uOHtDi4XGNVGv1gFkSfEcH6k"
        importerName: "default-importer"
        port: 8080
        replicaCount: 1

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: performance
                operator: In
                values:
                  - medium

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
