---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-init
  namespace: {{ .Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ .Values.gitops.repo }}
        revision: {{ .Values.gitops.revision }}
        directories:
          - path: cluster-init/*

  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: 'argocd-system'
      project: default # TODO
      source:
        repoURL: {{ .Values.gitops.repo }}
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-critical
  namespace: {{ .Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ .Values.gitops.repo }}
        revision: {{ .Values.gitops.revision }}
        directories:
          - path: cluster-critical/*

  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{path.basename}}` }}'
      project: default # TODO
      source:
        repoURL: {{ .Values.gitops.repo }}
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-platform
  namespace: {{ .Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ .Values.gitops.repo }}
        revision: {{ .Values.gitops.revision }}
        directories:
          - path: cluster-platform/*

  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{path.basename}}` }}'
      project: default # TODO
      source:
        repoURL: {{ .Values.gitops.repo }}
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: {{ .Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ .Values.gitops.repo }}
        revision: {{ .Values.gitops.revision }}
        directories:
          - path: cluster-apps/*

  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{path.basename}}` }}'
      project: default # TODO
      source:
        repoURL: {{ .Values.gitops.repo }}
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
