{{- range $index, $stack := .Values.stacks }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $stack.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  generators:
    - merge:
        mergeKeys:
          - path
        generators:
          - git:
              repoURL: {{ $.Values.gitops.repo }}
              revision: {{ $.Values.gitops.revision }}
              directories:
                - path: {{ $stack.name }}/*
          - git:
              repoURL: {{ $.Values.gitops.repo }}
              revision: {{ $.Values.gitops.revision }}
              files:
                - path: {{ $stack.name }}/**/config.json
          
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ .orNamespace | default $stack.namespace | default `{{path.basename}}` }}'
      project: default # TODO
      source:
        repoURL: {{ $.Values.gitops.repo }}
        path: '{{ `{{path}}` }}'
      syncPolicy:
        {{- if ne $stack.autosync_enabled false }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
{{- end }}
