---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-init
  namespace: argocd-system
spec:
  generators:
    - git:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        revision: 'master'
        directories:
          - path: cluster-init/*

  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: argocd-system
      project: default # TODO
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          jsonPointers:
            - /data/oidc.config
        - group: ""
          kind: Secret
          jsonPointers:
            - /data/oidc.authentik.clientSecret
      source:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-critical
  namespace: argocd-system
spec:
  generators:
    - git:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        revision: 'master'
        directories:
          - path: cluster-critical/*
          # - path: cluster-critical/monitoring-stack
          #   exclude: true
    # - git:
    #     repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
    #     revision: 'master'
    #     files:
    #       - path: cluster-apps/**/config.json
    #     template:
    #       metadata: {}
    #       spec:
    #         destination:
    #           name: in-cluster
    #           namespace: '{{ `{{path.basename}}` }}'
    #         project: default # TODO
    #         source:
    #           repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
    #           path: '{{ `{{path}}` }}'
    #           helm:
    #             skipCrds: true
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{path.basename}}` }}'
      project: default # TODO
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: grafana-oidc-secret
          namespace: monitoring-stack
          jsonPointers:
            - /data
      source:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        path: '{{ `{{path}}` }}'
        helm:
          skipCrds: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-platform
  namespace: argocd-system
spec:
  generators:
    - git:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        revision: 'master'
        directories:
          - path: cluster-platform/*

  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{path.basename}}` }}'
      project: default # TODO
      source:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd-system
spec:
  generators:
    - git:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        revision: 'master'
        files:
          - path: cluster-apps/**/config.json
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ `{{values.namespace}}` }}'
      project: default # TODO
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          jsonPointers:
            - /data/oidc.config
        - group: ""
          kind: Secret
          jsonPointers:
            - /data/oidc.authentik.clientSecret
      source:
        repoURL: 'https://github.com/mikevader/k3s-cluster-infra-apps.git'
        path: '{{ `{{path}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
