---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-access-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: firefly-access-token
  data:
    - secretKey: accessToken
      remoteRef:
        key: secret/data/framsburg/firefly
        property: accessToken
    - secretKey: token
      remoteRef:
        key: secret/data/framsburg/firefly
        property: accessToken
    - secretKey: cmdLineToken
      remoteRef:
        key: secret/data/framsburg/firefly
        property: cmdLineToken
