wiki:
  replicacount: 1

  image:
    repository: requarks/wiki
    tag: 2.5.300

  # nodeSelector:
  #   kubernetes.io/arch: arm64

  # affinity:
  #   nodeAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 50
  #         preference:
  #           matchExpressions:
  #             - key: performance
  #               operator: In
  #               values:
  #                 - medium

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    ingressClassName: traefik
    hosts:
      - host: 'wiki.framsburg.ch'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: ['wiki.framsburg.ch']
        secretName: 'wiki-framsburg-ch-tls'

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  postgresql:
    enabled: false
    postgresqlHost: wiki-test-rw.wiki.svc
    postgresqlDatabase: app
    postgresqlUser: app
    existingSecret: wiki-test-app
    existingSecretKey: password
