apiVersion: v2
name: torrent
description: Torrent clients
version: 1.0.0
dependencies:
  - name: transmission
    version: 8.4.14
    repository: https://mikevader.github.io/charts
  - name: flood
    version: 6.4.17
    repository: https://mikevader.github.io/charts
