apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: promtail-secret
  namespace: promtail
  labels:
    app.kubernetes.io/part-of: promtail
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: promtail
    meta.helm.sh/release-namespace: promtail
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: promtail-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: promtail
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: promtail
          meta.helm.sh/release-namespace: promtail
  data:
    - secretKey: license.id
      remoteRef:
        key: secret/data/framsburg/promtail/license
        property: id
    - secretKey: license.key
      remoteRef:
        key: secret/data/framsburg/promtail/license
        property: key
