apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nolock-nfs
mountOptions:
  - nolock
provisioner: driver.longhorn.io
parameters:
  fsType: ext4
  numberOfReplicas: '3'
  staleReplicaTimeout: '30'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
