apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nolock-nfs
  annotations:
mountOptions:
- nolock
provisioner: driver.longhorn.io
parameters:
  fsType: ext4
  numberOfReplicas: '2'
  staleReplicaTimeout: '30'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
