---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: longhorn # longhorn-test-access-key
  AWS_SECRET_ACCESS_KEY: longhorn # longhorn-test-secret-key
  AWS_ENDPOINTS: http://michaels-mini.local:9000/longhorn