---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4=
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4=
  AWS_ENDPOINTS: aHR0cDovL21pY2hhZWxzLW1pbmkubG9jYWw6OTAwMA==