apiVersion: v2
name: argocd
description: Bootstrap Chart for Argo CD
version: 0.0.0
dependencies:
  - name: argo-cd
    version: 3.35.4
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-applicationset
    version: 1.11.0
    repository: https://argoproj.github.io/argo-helm
    alias: applicationset
