apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: init
spec:
  generators:
  - git:
      repoURL: https://github.com/mikevader/k3s-cluster-infra-apps.git
      revision: master
      directories:
      - path: cluster-init/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
      project: default
      source:
        repoURL: https://github.com/mikevader/k3s-cluster-infra-apps.git
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
