apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: init
  namespace: argocd-system
spec:
  generators:
  - git:
      repoURL: https://github.com/mikevader/k3s-cluster-infra-apps.git
      revision: master
      directories:
      - path: cluster-init/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      destination:
        name: in-cluster
        namespace: argocd-system
      project: default
      source:
        repoURL: https://github.com/mikevader/k3s-cluster-infra-apps.git
        path: '{{ path }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
