firefly:
  firefly-db:
    enabled: false


  firefly-iii:
    image:
      tag: "version-6.0.16"

    config:
      env:
        APP_URL: 'https://firefly2.framsburg.ch'
        DB_CONNECTION: pgsql
        DB_HOST: hello-world.postgres-operator.svc
        DB_PORT: "5432"
        DB_DATABASE: fireflydb
        DB_USERNAME: firefly
        DEFAULT_LANGUAGE: "en_US"
        DEFAULT_LOCALE: "equal"
        TZ: "Europe/Zurich"
        TRUSTED_PROXIES: "**"

    # -- Create a new Secret from values file to store sensitive environment variables. Make sure to keep your secrets encrypted in the repository! For example, you can use the 'helm secrets' plugin (https://github.com/jkroepke/helm-secrets) to encrypt and manage secrets. If the 'config.existingSecret' value is set, a new Secret will not be created.
    secrets:
      env:
        APP_KEY: 'SomeRandomStringOf32CharsExactly'
        APP_PASSWORD: "CHANGE_ENCRYPT_ME"
        DB_PASSWORD: "ojfFYz1kdNGQiEFdG1RRaQH5fLd2LmoOHd5to5WQLFr3swgliyMqu178W7iZ75Y0"

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: performance
                  operator: In
                  values:
                    - medium

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      className: traefik
      hosts:
        - 'firefly2.framsburg.ch'
      tls:
        - hosts: ['firefly2.framsburg.ch']
          secretName: 'firefly2-framsburg-ch-tls'

  importer:
    enabled: true
    image:
      tag: "version-1.3.1"

    fireflyiii:
      url: 'https://firefly2.framsburg.ch'
      auth:
        accessToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTdkNWFlMDMwNjIxYTQ0MDI5ZmEwNzc3MjVhYTE5MDMxNTI2ZWU0ZGU1ZjQwNjM0YjVhYjlmMzRkZWU3NThkNzhiYjBiNDQ4MjRjMjY0ZDEiLCJpYXQiOjE2ODkwMjQ5NTEuMTExOTcxLCJuYmYiOjE2ODkwMjQ5NTEuMTExOTczLCJleHAiOjE3MjA2NDczNTEuMDY3NTgsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.GDc2uI9mxhV0OmvCgEeOYX4L4YK3AoFp09rHcp7xRknTipdPYG_NirYvhdW2VMlgz1SuX61AKX0z1anPkgwkHtC7VdJyQqt6FgR0VTWmSz6sfc7nErUSdLr671SCsgFafugBJLXfaGEoJ1b4Nyj0BhhmcROPu3im6FmYnCCgIHjrzRd5Ax262U4N2JbcCgBvd8_XLDPo1k2AlXgCu1Q_yR-IfpJa1z-Nm0PLClWk70iZ2ebfvsdcri71Fof7uEPIB3lDx0tHLMrXSJ-xIz5omaQ9zzW8dkzpBo6kc4wYm3wA_z2XB4MWXmWtGDDK-Ipl0fTRMy25Ebo-KBilCGLxGj0iyI6M-D9tNXWRypjCOk3278z51d-J9wGMMHYnYSTVjXk3bv_3SLnNsKcF_xBvfoM6DSJWirpONcYdgskxr57XshvtXuU7fWEHcCWiXLfZU5nsXk5327xlf9ENuV1DKrCkllWW-POesllFDnxhXXhOVangBcI7sfxcjhznc0aP6uYdVblnExa0kALtErBuxJfOz1h5Zd6sTx2baAfKkDYqFhOg_ygqF1vKGBVy9FUfHgEYTeWvPeI_hYEM7q5T1FQPyRoQHbp2w3JZ3oIw6fTpIgo_RfSbpdcG99B-uNXGhONCwP_Gh4uqzIwbeKkdb2opJANnN0uTYjEUqvXEyqg'

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: performance
                  operator: In
                  values:
                    - medium

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      className: traefik
      hosts:
        - 'firefly2import.framsburg.ch'
      tls:
        - hosts: ['firefly2import.framsburg.ch']
          secretName: 'firefly2import-framsburg-ch-tls'
