firefly:
  firefly-iii:
    image:
      tag: "version-6.0.16"

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: performance
                  operator: In
                  values:
                    - medium

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      className: traefik
      hosts:
        - host: 'firefly2.framsburg.ch'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['firefly2.framsburg.ch']
          secretName: 'firefly2-framsburg-ch-tls'

  importer:
    enabled: true
    image:
      tag: "version-1.3.1"

    fireflyiii:
      url: 'https://firefly2.framsburg.ch'

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: performance
                  operator: In
                  values:
                    - medium

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      className: traefik
      hosts:
        - host: 'import-firefly2.framsburg.ch'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['import-firefly2.framsburg.ch']
          secretName: 'import-firefly2-framsburg-ch-tls'
