---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actualbudget-openid-secret
  labels:
    app.kubernetes.io/part-of: actual
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: actualbudget-openid-secret
    metadata:
      labels:
        app.kubernetes.io/part-of: actual
        app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: clientId
      remoteRef:
        key: secret/data/framsburg/actual
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: secret/data/framsburg/actual
        property: clientSecret
