---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-plex-migration
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jellyfin-plex-migration
  data:
    - secretKey: plex-token
      remoteRef:
        key: secret/data/framsburg/jellyfin
        property: plex-token
    - secretKey: jellyfin-token
      remoteRef:
        key: secret/data/framsburg/jellyfin
        property: jellyfin-token
    - secretKey: jellyfin-user
      remoteRef:
        key: secret/data/framsburg/jellyfin
        property: jellyfin-user

