---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
  labels:
    app.kubernetes.io/part-of: openclaw
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openclaw-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: openclaw
          app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: api_key

