---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
  labels:
    app.kubernetes.io/part-of: openclaw
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openclaw-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: openclaw
          app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: NVIDIA_API_KEY
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: moonshot_api_key
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: gateway_token
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: discord_bot_token
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: openai_api_key
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: anthropic_api_key
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: gemini_api_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-git-token
  namespace: openclaw
  labels:
    app.kubernetes.io/part-of: openclaw
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openclaw-git-token
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: openclaw
          app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: github-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-gog
  namespace: openclaw
  labels:
    app.kubernetes.io/part-of: openclaw
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openclaw-gog
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: openclaw
          app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: GOG_ACCOUNT
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: gog_account
    - secretKey: GOG_KEYRING_PASSWORD
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: gog_keyring_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-git-creds
  namespace: openclaw
  labels:
    app.kubernetes.io/part-of: openclaw
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-git-creds
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: openclaw
          app.kubernetes.io/managed-by: Helm
      stringData:
        credentials: |
          '{{ .github_credentials }}'
  data:
    - secretKey: github_credentials
      remoteRef:
        key: secret/data/framsburg/openclaw
        property: github_credentials
