---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: externalOnInternal
  namespace: metallb-system
spec:
  addresses:
  - 192.168.42.160-192.168.42.169
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement3
  namespace: metallb-system
spec:
  ipAddressPools:
    - externalOnInternal
  interfaces:
    - ens18
    - eth0
