---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external
  namespace: metallb-system
spec:
  addresses:
  - 192.168.99.150-192.168.99.159
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement2
  namespace: metallb-system
spec:
  ipAddressPools:
    - external
  interfaces:
    - ens18.99
    - eth0.99
