---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: metallb-external-ip-range
  namespace: metallb-system
spec:
  addresses:
  - 192.168.99.150-192.168.99.152
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement2
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-external-ip-range
status: {}

