---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4=
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4=
  AWS_ENDPOINTS: aHR0cHM6Ly9taW5pby5mcmFtc2J1cmcubmV0
