---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4=
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4=
  AWS_ENDPOINTS: aHR0cHM6Ly9taW5pby5mcmFtc2J1cmcubmV0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio2-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio2-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: longhorn-system
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/data/framsburg/longhorn/minio-secret
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data/framsburg/longhorn/minio-secret
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: secret/data/framsburg/longhorn/minio-secret
        property: AWS_ENDPOINTS
