---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nfs-v1
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  nfsOptions: "vers=4.1,noresvport,softerr,timeo=600,retrans=5"
