apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:
  AWS_ENDPOINT: 'https://minio.framsburg.ch'
  WALE_S3_ENDPOINT: 'https+path://minio.framsburg.ch'
  WALE_S3_PREFIX: "$WAL_S3_BUCKET/spilo/{WAL_BUCKET_SCOPE_PREFIX}{SCOPE}{WAL_BUCKET_SCOPE_SUFFIX}/wal/{PGVERSION}"
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '*/30 * * * *'
  AWS_S3_FORCE_PATH_STYLE: "true" # needed for MinIO
  AWS_REGION: us-east-1
  WALG_DISABLE_S3_SSE: "true"
  BACKUP_NUM_TO_RETAIN: "5"
  CLONE_USE_WALG_RESTORE: "true"
