apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pod-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pod-secrets
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/data/framsburg/postgres-operator/pod-secrets
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data/framsburg/postgres-operator/pod-secrets
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pod-secrets-ca
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pod-secrets-ca
  data:
    - secretKey: MINIO_CA_FILE
      remoteRef:
        key: secret/data/framsburg/postgres-operator/ca-file
        property: MINIO_CA_FILE
