spc:
  enabled: false
  provider: vault
  role: csi-secrets-store
  vaultAddress: 'https://vault.framsburg.ch'
  defaultSecretMountPath: kv-v2
  defaultObjectPath: ""
  secretObjects: false
  extraSecretObjects: []
  objects:
    - name: config.php
      key: config.php
      mount: kv-v2
      path: 'k8s/framsburg/backbone'
      secretName: ""
