global:
  domainName: filebrowser.framsburg.ch

filebrowser:
  controller:
    enabled: true
  env:
    TZ: Europe/Zurich

  config: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/config/database.db",
      "root": "/mnt/media",
      "auth": {
        "method": "proxy",
        "header": "X-authentik-username"
      }
    }

  podSecurityContext:
    # runAsUser: 666
    # runAsGroup: 666
    fsGroup: 666
    fsGroupChangePolicy: Always

  service:
    main:
      ports:
        http:
          port: 8080

  persistence:
    config:
      enabled: true
      type: pvc
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce

    audiobooks:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-audiobooks
      mountPath: /mnt/media/audiobooks

    movies:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies
      mountPath: /mnt/media/movies

#    # tv:
#    #   enabled: true
#    #   type: pvc
#    #   retain: true
#    #   storageClass: "-"
#    #   existingClaim: plex-tv
#    #   mountPath: /mnt/media/tv

    tv-abcd:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-abcd
      mountPath: /mnt/media/tv-abcd

    tv-efgh:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-efgh
      mountPath: /mnt/media/tv-efgh

    tv-mnop:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-mnop
      mountPath: /mnt/media/tv-mnop

    tv-qrst:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-qrst
      mountPath: /mnt/media/tv-qrst

    tv-all:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-all
      mountPath: /mnt/media/tv-all

    downloads:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: torrent-transmission-downloads
      mountPath: /mnt/media/downloads

    tv2:
      enabled: true
      readonly: true
      type: hostPath
      hostPath: /mnt/media/tvshows
      hostPathType: Directory
      mountPath: /mnt/media/tv2

    movies2:
      enabled: true
      readonly: true
      type: hostPath
      hostPath: /mnt/media/movies
      hostPathType: Directory
      mountPath: /mnt/media/movies2
    movies-all:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies-all
      mountPath: /mnt/media/movies-all


    tv-uhd:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-uhd
      mountPath: /mnt/media/tv-uhd
    tv-uhd-all:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-uhd-all
      mountPath: /mnt/media/tv-uhd-all

    movies-uhd:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies-uhd
      mountPath: /mnt/media/movies-uhd
    movies-uhd-all:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies-uhd-all
      mountPath: /mnt/media/movies-uhd-all

#  affinity:
#    podAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: app.kubernetes.io/name
#                operator: In
#                values:
#                  - plex
#          topologyKey: kubernetes.io/hostname

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # traefik.ingress.kubernetes.io/router.priority: "10"
        # traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
              service:
                name: filebrowser
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
