global:
  domainName: filebrowser.framsburg.ch

filebrowser:
  controller:
    enabled: true
    annotations:
      "sidecar.jaegertracing.io/inject": "true"
  env:
    TZ: Europe/Zurich
    JAEGER_AGENT_HOST:
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

  config: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/config/database.db",
      "root": "/mnt/media",
      "auth": {
        "method": "proxy",
        "header": "X-authentik-username"
      }
    }

  podSecurityContext:
    # runAsUser: 666
    # runAsGroup: 666
    fsGroup: 666
    fsGroupChangePolicy: Always

  service:
    main:
      ports:
        http:
          port: 8080

  persistence:
    config:
      enabled: true
      type: pvc
      size: 1Gi
      accessMode: ReadWriteOnce

    audiobooks:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-audiobooks
      mountPath: /mnt/media/audiobooks

    movies:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies
      mountPath: /mnt/media/movies

    # tv:
    #   enabled: true
    #   type: pvc
    #   retain: true
    #   storageClass: "-"
    #   existingClaim: plex-tv
    #   mountPath: /mnt/media/tv

    tv-abcd:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-abcd
      mountPath: /mnt/media/tv-abcd

    tv-efgh:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-efgh
      mountPath: /mnt/media/tv-efgh

    tv-mnop:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-mnop
      mountPath: /mnt/media/tv-mnop

    tv-qrst:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-qrst
      mountPath: /mnt/media/tv-qrst

    downloads:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: torrent-transmission-downloads
      mountPath: /mnt/media/downloads

    movies2:
      enabled: true
      readonly: true
      type: hostPath
      hostPath: /mnt/media2/movies
      hostPathType: Directory
      mountPath: /mnt/media/movies2
    tv2:
      enabled: true
      readonly: true
      type: hostPath
      hostPath: /mnt/media/root/TVShows
      hostPathType: Directory
      mountPath: /mnt/media/tv2

  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - plex
          topologyKey: kubernetes.io/hostname

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
              service:
                name: filebrowser
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
