global:
  domainName: filebrowser.framsburg.ch

filebrowser:
  controller:
    enabled: true
  env:
    TZ: Europe/Zurich

  config: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/config/database.db",
      "root": "/mnt/media",
      "authMethod": "proxy",
      "header": "X-authentik-username"
    }
  
  service:
    main:
      ports:
        http:
          port: 8080

  persistence:
    audiobooks:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-audiobooks
      mountPath: /mnt/media/audiobooks

    movies:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies
      mountPath: /mnt/media/movies

    # tv:
    #   enabled: true
    #   type: pvc
    #   retain: true
    #   storageClass: "-"
    #   existingClaim: plex-tv
    #   mountPath: /mnt/media/tv

    tv-abcd:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-abcd
      mountPath: /mnt/media/tv-abcd

    tv-efgh:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-efgh
      mountPath: /mnt/media/tv-efgh

    tv-mnop:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-mnop
      mountPath: /mnt/media/tv-mnop

    tv-qrst:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv-qrst
      mountPath: /mnt/media/tv-qrst

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
              service:
                name: filebrowser
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
