---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: samba
  namespace: plex

spec:
  entryPoints:
    - smb
  routes:
    - match: "HostSNI('{{ .Values.global.domainName }}')"
      services:
        - name: samba
          port: 445
