apiVersion: v2
name: postgres-operator
version: 0.0.0
dependencies:
  - name: postgres-operator
    version: 1.10.1
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    alias: operator
  # - name: postgres-operator-ui
  #   version: 1.10.0
  #   repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  #   alias: ui
