operator:
  configGeneral: {}

  configMajorVersionUpgrade:
    major_version_upgrade_mode: "manual"

  configKubernetes:
    enable_cross_namespace_secret: true
    pod_environment_configmap: "pod-config"
    pod_environment_secret: "pod-secrets"
    node_readiness_label:
      perfomance: medium

  configAwsOrGcp:
    additional_secret_mount: "pod-secrets-ca"
    additional_secret_mount_path: "/tlsca"
    aws_region: us-east-1

  configLogicalBackup: {}

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: performance
                operator: In
                values:
                  - medium

ui:
  envs:
    # IMPORTANT: While operator chart and UI chart are independent, this is the interface between
    # UI and operator API. Insert the service name of the operator API here!
    appUrl: "https://postgres.framsburg.ch"
    operatorApiUrl: "http://postgres-operator.postgres-operator.svc:8080"
    operatorClusterNameLabel: "cluster-name"
    resourcesVisible: "True"
    targetNamespace: "postgres-operator"
    teams:
      - "acid"

  extraEnvs:
    - name: AWS_ENDPOINT
      value: https://minio.framsburg.net
    - name: WALE_S3_ENDPOINT
      value: https+path://minio.framsburg.net
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: "pod-secrets"
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: "pod-secrets"
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_DEFAULT_REGION
      value: "us-east-1"
    - name: SPILO_S3_BACKUP_BUCKET
      value: "postgres-backups"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    ingressClassName: traefik
    hosts:
      - host: postgres.framsburg.ch
        paths: [""]
    tls:
     - secretName: postgres-framsburg-ch-tls
       hosts:
         - postgres.framsburg.ch
