nginx:
  controller:
    service:
      annotations:
        metallb.universe.tf/address-pool: externalOnInternal
        metallb.universe.tf/allow-shared-ip: shared-external

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    serviceMonitor:
      create: true
