nginx:
  controller:
    service:
      annotations:
        metallb.universe.tf/address-pool: external-on-internal
        metallb.universe.tf/allow-shared-ip: shared-external

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    serviceMonitor:
      create: true

  tcp:
    30402: plex/torrent-transmission-utptcp:30402
    51413: hidden/transmission-utptcp:51413

  udp:
    30402: plex/torrent-transmission-utpudp:30402
    # 51413: hidden/transmission-utpudp:51413
