nginx:
  controller:
    service:
      annotations:
        metallb.universe.tf/address-pool: metallb-external-ip-range
        metallb.universe.tf/allow-shared-ip: shared-external

    serviceMonitor:
      create: true

  serviceInsight:
    create: true
