apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-oidc-secret
  namespace: vault
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-oidc-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: vault
  data:
    - secretKey: oidc-id
      remoteRef:
        key: secret/data/framsburg/vault/oidc
        property: client-id
    - secretKey: oidc-secret
      remoteRef:
        key: secret/data/framsburg/vault/oidc
        property: client-secret

