apiVersion: v1
kind: Secret
metadata:
  name: vault-oidc-secret
  namespace: vault
  labels:
    app.kubernetes.io/part-of: vault
  # annotations:
  #   vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc:8200"
  #   vault.security.banzaicloud.io/vault-path: "kubernetes"
  #   vault.security.banzaicloud.io/vault-role: "vault"
  #   vault.security.banzaicloud.io/vault-skip-verify: "true" 
data:
  oidc-id: MGVkMGMxZTA5NjZhOTE1NGY4Zjk5ZjE5ODI0ZWRjZTIxNmM2ZWU2ZA==
  oidc-secret: ZWJjMjU4NmI5OTNlZjQ2ZGMzMGIwMDAxNjk0OGJmN2E4YjM4Y2NlYWUzZDMzZGQ0MDE5ZTRhOWIzNjVhNTdiZjQ5NDIzMWQ1YTM4MmE5MjlmMjQyYTNmMzNkYzJhN2M0NmE3NDQ0NjZiYTYyNDMwNGM2OGU0MWIxZGIwNjAxZWE=
type: Opaque
