---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgres-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-credentials
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: password
