---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database-secret
  data:
    - secretKey: databaseName
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: database
    - secretKey: databaseUsername
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: username
    - secretKey: databasePassword
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: password
    - secretKey: superuserUsername
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: superuserUsername
    - secretKey: superuserPassword
      remoteRef:
        key: secret/data/framsburg/authentik/postgres
        property: superuserPassword
