---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-dex
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "dex-app"
    objects: |
      - objectName: "oidc-id"
        secretPath: "kv-v2/data/k8s/framsburg/dex"
        secretKey: "client-id"
      - objectName: "oidc-secret"
        secretPath: "kv-v2/data/k8s/framsburg/dex"
        secretKey: "client-secret"
  secretObjects:
    - data:
        - key: id
          objectName: oidc-id
        - key: secret
          objectName: oidc-secret
      secretName: oidc
      type: Opaque
