apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opsgenie-secret
  namespace: monitoring-stack
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring-stack
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: opsgenie
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: kube-prometheus-stack
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: kube-prometheus-stack
          meta.helm.sh/release-namespace: monitoring-stack
  data:
    - secretKey: opsgenie-apikey
      remoteRef:
        key: secret/data/framsburg/prometheus/opsgenie
        property: apikey
