{
 "title": "Alert Dashboard",
 "tags": [ "alertmanager" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "severity", "label": "Severity", "query": { "query": "label_values(ALERTS,severity)" } },
   { "name": "alertname", "label": "Alertname", "query": { "query": "label_values(ALERTS,alertname)" } },
   {
    "name": "state",
    "label": "State",
    "query": {
     "query": "label_values(ALERTS,alertstate)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(ALERTS,namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~\"$alertname\", alertstate=~\"$state\", namespace=~\"$namespace\", severity=~\"$severity\"})"
    }
   ]
  },
  {
   "title": "Total Warning",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~\"$alertname\", alertstate=~\"$state\", namespace=~\"$namespace\", severity=~\"warning\"})"
    }
   ]
  },
  {
   "title": "Total Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~\"$alertname\", alertstate=~\"$state\", namespace=~\"$namespace\", severity=~\"critical\"})"
    }
   ]
  },
  {
   "title": "Instance Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~\"InstanceDown\", alertstate=~\"$state\", namespace=~\"$namespace\", severity=~\"$severity\"})"
    }
   ]
  },
  {
   "title": "Service Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~\"ServiceDown\", alertstate=~\"$state\", namespace=~\"$namespace\", severity=~\"$severity\"})"
    }
   ]
  },
  {
   "title": "Service Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~\".*MemoryUtilization\", alertstate=~\"$state\", namespace=~\"$namespace\", severity=~\"$severity\"})"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 } }
 ]
}