apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring-stack
  labels:
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring-stack
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: kube-prometheus-stack
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: kube-prometheus-stack
          meta.helm.sh/release-namespace: monitoring-stack
  data:
    - secretKey: oidc-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/framsburg/grafana/oidc
        property: client-id
    - secretKey: oidc-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/framsburg/grafana/oidc
        property: client-secret
