apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-ext
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
  data:
    - secretKey: admin.password
      remoteRef:
        key: secret/data/framsburg/argocd/secrets
        property: admin.password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: secret/data/framsburg/argocd/secrets
        property: admin.passwordMtime
    - secretKey: server.secretkey
      remoteRef:
        key: secret/data/framsburg/argocd/secrets
        property: server.secretkey
    - secretKey: webhook.github.secret
      remoteRef:
        key: secret/data/framsburg/argocd/secrets
        property: webhook.github.secret
    - secretKey: oidc.authentik.clientSecret
      remoteRef:
        key: secret/data/framsburg/argocd/oidc
        property: client-secret
    - secretKey: oidc.authentik.clientId
      remoteRef:
        key: secret/data/framsburg/argocd/oidc
        property: client-id
