apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret-ext
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
  data:
    - secretKey: admin.password
      remoteRef:
        key: secret/data/framsburg/argocd/secret
        property: admin.password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: secret/data/framsburg/argocd/secret
        property: admin.passwordMtime
    - secretKey: sever.secretkey
      remoteRef:
        key: secret/data/framsburg/argocd/secret
        property: sever.secretkey
    - secretKey: webhook.github.secret
      remoteRef:
        key: secret/data/framsburg/argocd/secret
        property: webhook.github.secret
