apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-secret
  namespace: argocd-system
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argocd-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: argo-cd
          meta.helm.sh/release-namespace: argocd-system
  data:
    - secretKey: webhook.github.secret
      remoteRef:
        key: secret/data/framsburg/argocd/github
        property: webhook-secret
