---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-framsburg-ch-tls
  namespace: argocd-system
spec:
  secretName: argocd-framsburg-ch-tls
  dnsNames:
    - argocd.framsburg.ch
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
