---
apiVersion: v2
name: dmw
description: Dungeon Master Workshop app
version: 1.0.0
dependencies:
  - name: dmw
    repository: https://mikevader.github.io/dm-workshop
    version: 1.0.0-dev.4c36ba3
