---
dmw:
  railsEnvironment: production

  annotations:
    "sidecar.jaegertracing.io/inject": "true"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    hosts:
      - host: 'dmw.framsburg.ch'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: ['dmw.framsburg.ch']
        secretName: 'dmw-framsburg-ch-tls'

  env:
    - name: SERVER_HOST_NAME
      value: 'dmw.framsburg.ch'
    - name: MAIL_HOST
      value: 'dmw.framsburg.ch'
    - name: SMTP_DEFAULT_FROM
      value: 'noreply@dmw.framsburg.ch'
    - name: SENDGRID_API_KEY
      valueFrom:
        secretKeyRef:
          name: dmw
          key: SENDGRID_API_KEY
    - name: SECRET_KEY_BASE
      valueFrom:
        secretKeyRef:
          name: dmw
          key: SECRET_KEY_BASE
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: dmw-app
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dmw-app
          key: password
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: dmw-app
          key: host
    - name: DATABASE_PORT
      valueFrom:
        secretKeyRef:
          name: dmw-app
          key: port
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: dmw-app
          key: dbname
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: dmw-app
          key: uri

# podSecurityContext:
#  sysctls:
#    - name: fs.inotify.max_user_instances
#      value: "256"
