---
dmw:
  railsEnvironment: development

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    hosts:
      - host: 'dmw.framsburg.ch'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: ['dmw.framsburg.ch']
        secretName: 'dmw-framsburg-ch-tls'

  env:
    - name: SERVER_HOST_NAME
      value: 'dmw.framsburg.ch'

# podSecurityContext:
#  sysctls:
#    - name: fs.inotify.max_user_instances
#      value: "256"
