---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-only-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: oidc:fb-users
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: oidc:fb-admins
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: oidc:akadmin
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: oidc:michael@anduin.ch
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: fb-admins
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: akadmin
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: michael@anduin.ch
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
