---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oidc-secret
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: secret/data/framsburg/headlamp/oidc
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: secret/data/framsburg/headlamp/oidc
        property: client_secret
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: secret/data/framsburg/headlamp/oidc
        property: issuer_url
    - secretKey: OIDC_SCOPES
      remoteRef:
        key: secret/data/framsburg/headlamp/oidc
        property: scopes
