weblate:
  siteDomain: weblate.framsburg.ch

  existingSecret: weblate-secrets

  extraConfig:
    CSRF_TRUSTED_ORIGINS: "https://weblate.framsburg.ch,https://*.framsburg.ch"
    WEBLATE_ALLOWED_HOSTS: "weblate.framsburg.ch,*"
    WEBLATE_REGISTRATION_OPEN: "0"
    WEBLATE_TIME_ZONE: "Europe/Zurich"
    CSRF_COOKIE_SECURE: "True"
    SESSION_COOKIE_SECURE: "True"
    SECURE_SSL_REDIRECT: "True"

  postgresql:
    enabled: false
    postgresqlHost: weblate-rw
    auth:
      database: app
      userName: app
      existingSecret: weblate-app
      secretKeys:
        userPasswordKey: password

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # traefik.ingress.kubernetes.io/router.middlewares: weblate-svc-weblate-headers@kubernetescrd
    ingressClassName: traefik
    hosts:
      - host: weblate.framsburg.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: weblate-framsburg-ch-tls
        hosts:
          - weblate.framsburg.ch
