argocdNamespace: monitoring
kube-prometheus-stack:
  kubeEtcd:
    enabled: false

  prometheusOperator:
    admissionWebhooks:
      enabled: false
      certManager:
        enabled: true
        certRef:
          name: "issuer"
          kind: "ClusterIssuer"

  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - grafana.framsburg.ch
      tls:
        - secretName: grafana-framsburg-ch-tls
          hosts:
            - grafana.framsburg.ch
    sidecar:
      dashboards:
        searchNamespace: ALL
      datasources:
        searchNamespace: ALL
    plugins:
      - grafana-piechart-panel
    grafana.ini:
      server:
        root_url: https://grafana.framsburg.ch

  alertmanager:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - alertmanager.framsburg.ch
      tls:
        - secretName: alertmanager-framsburg-ch-tls
          hosts:
            - alertmanager.framsburg.ch

  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - prometheus.framsburg.ch
      tls:
        - secretName: prometheus-framsburg-ch-tls
          hosts:
            - prometheus.framsburg.ch

    thanosIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - thanos.framsburg.ch
      tls:
        - secretName: thanos-framsburg-ch-tls
          hosts:
            - thanos.framsburg.ch

