---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secrets
  namespace: hermes
  labels:
    app.kubernetes.io/part-of: hermes
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hermes-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: hermes
          app.kubernetes.io/managed-by: Helm
  data:
    - secretKey: discord-token
      remoteRef:
        key: secret/data/framsburg/hermes
        property: discordToken
