vault:
  server:
    image:
      repository: "vault"
      tag: "1.9.1"
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
      hosts:
        - host: vault.framsburg.ch
          paths: [/]
      tls:
        - hosts: [vault.framsburg.ch]
          secretName: vault-framsburg-ch-tls
  dataStorage:
    storageClass: longhorn
  ui:
    enabled: true
  csi:
    enabled: false
  injector:
    enabled: false

  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 256Mi
