---
# Provides the required permissions for readonly users
# to get metrics working in lens
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: port-forward-lens
  namespace: monitoring-stack
rules:
- apiGroups: [""]
  resources: ["pods/portforward", "services/proxy"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-lens-binding
  namespace: monitoring-stack
subjects:
  - kind: User
    name: default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: port-forward-lens
  apiGroup: rbac.authorization.k8s.io
