apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: driver-config-file-secret
  namespace: democratic-csi
  labels:
    app.kubernetes.io/part-of: democratic-csi
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: democratic-csi
    meta.helm.sh/release-namespace: democratic-csi
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: driver-config-file-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: democratic-csi
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: democratic-csi
          meta.helm.sh/release-namespace: democratic-csi
  data:
    - secretKey: "driver-config-file.yaml"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Auto
        key: secret/data/framsburg/truenas/truenas
        property: secret_data
