# Replace path with regex
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: replace-with-web
  namespace: plex
spec:
  replacePathRegex:
    regex: ^/(.*)
    replacement: /web/$1
