promtail:
  # serviceMonitor:
  #   enabled: true
  config:
    #serverPort: 3100
    clients:
      - url: http://loki-gateway.loki.svc/loki/api/v1/push
        tenant_id: "1"

    limit_config:
      readline_rate: 800
      readline_burst: 800
      readline_rate_enabled: true

    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
            idle_timeout: 60s
            label_structured_data: yes
            labels:
              job: syslog
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: host
            - source_labels: ['__syslog_message_hostname']
              target_label: hostname
            - source_labels: ['__syslog_message_severity']
              target_label: 'level'
            - source_labels: ['__syslog_message_severity']
              target_label: 'severity'
            - source_labels: ['__syslog_message_facility']
              target_label: 'facility'
            - source_labels: ['__syslog_message_app_name']
              target_label: 'application'
            - source_labels: ['__syslog_connection_hostname']
              target_label: 'connection_hostname'
          pipeline_stages:
            - match:
                selector: '{host="OPNsense.local"}'
                stages:
                  - regex:
                      expression: '^(?P<message>(?P<rule>[^,]*),(?P<sub_rule>[^,]*),(?P<anchor>[^,]*),(?P<tracker>[^,]*),(?P<interface>[^,]*),(?P<reason>[^,]*),(?P<action>[^,]*),(?P<direction>[^,]*),(?P<ip_version>[^,]*),(?P<tos>[^,]*),(?P<ecn>[^,]*),(?P<ttl>[^,]*),(?P<id>[^,]*),(?P<offset>[^,]*),(?P<flags>[^,]*),(?P<protocol_id>[^,]*),(?P<protocol>tcp),(?P<length>[^,]*),(?P<source_ip>[^,]*),(?P<destination_ip>[^,]*),(?P<source_port>[^,]*),(?P<destination_port>[^,]*),(?P<data_length>[^,]*),(?P<tcp_flags>[^,]*),(?P<sequence_number>[^,]*),(?P<ack_number>[^,]*),(?P<tcp_window>[^,]*),(?P<urg>[^,]*),(?P<tcp_options>[^,]*))$'
                  - regex:
                      expression: '^(?P<message>(?P<rule>[^,]*),(?P<sub_rule>[^,]*),(?P<anchor>[^,]*),(?P<tracker>[^,]*),(?P<interface>[^,]*),(?P<reason>[^,]*),(?P<action>[^,]*),(?P<direction>[^,]*),(?P<ip_version>[^,]*),(?P<tos>[^,]*),(?P<ecn>[^,]*),(?P<ttl>[^,]*),(?P<id>[^,]*),(?P<offset>[^,]*),(?P<flags>[^,]*),(?P<protocol_id>[^,]*),(?P<protocol>udp),(?P<length>[^,]*),(?P<source_ip>[^,]*),(?P<destination_ip>[^,]*),(?P<source_port>[^,]*),(?P<destination_port>[^,]*),(?P<data_length>[^,]*))$'
                  - regex:
                      expression: '^(?P<message>(?P<rule>[^,]*),(?P<sub_rule>[^,]*),(?P<anchor>[^,]*),(?P<tracker>[^,]*),(?P<interface>[^,]*),(?P<reason>[^,]*),(?P<action>[^,]*),(?P<direction>[^,]*),(?P<ip_version>[^,]*),(?P<tos>[^,]*),(?P<ecn>[^,]*),(?P<ttl>[^,]*),(?P<id>[^,]*),(?P<offset>[^,]*),(?P<flags>[^,]*),(?P<protocol_id>[^,]*),(?P<protocol>icmp|igmp|gre),(?P<length>[^,]*),(?P<source_ip>[^,]*),(?P<destination_ip>[^,]*),(?P<data>[^,]*))$'
                  - geoip:
                      db: "/mnt/geoipdb/GeoLite2-City.mmdb"
                      source: "source_ip"
                      db_type: "city"
                  - labels:
                      interface:
                      action:
                      direction:
                      protocol:
                      source_ip:

  initContainer:
    - name: geo-ip
      image: ghcr.io/maxmind/geoipupdate:v6.0
      volumeMounts:
        - name: geoipdb
          mountPath: /etc/geoip
      env:
        - name: GEOIPUPDATE_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: promtail-secret
              key: license.id
        - name: GEOIPUPDATE_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: promtail-secret
              key: license.key
        - name: GEOIPUPDATE_EDITION_IDS
          value: "GeoLite2-City GeoLite2-Country"
        - name: GEOIPUPDATE_DB_DIR
          value: "/etc/geoip"

  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 514
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.42.151
  
  extraVolumeMounts:
    - name: geoipdb
      mountPath: /mnt/geoipdb

  extraVolumes:
    - name: geoipdb
      emptydir: {}

  # # Mount journal directory into promtail pods
  # extraVolumes:
  #   - name: journal
  #     hostPath:
  #       path: /var/log/journal

  # extraVolumeMounts:
  #   - name: journal
  #     mountPath: /var/log/journal
  #     readOnly: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
  # readinessProbe:
  #   successThreshold: 1
  #   timeoutSeconds: 1
  # resources:
  #   requests:
  #     cpu: 50m
  #     memory: 48Mi
  #   limits:
  #     cpu: 800m
  #     memory: 96Mi
