promtail:
  # serviceMonitor:
  #   enabled: true
  config:
    #serverPort: 3100
    clients:
      - url: http://loki-gateway.loki.svc/loki/api/v1/push
        tenant_id: "1"

    limit_config:
      readline_rate: 800
      readline_burst: 800
      readline_rate_enabled: true

    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: firewall
          syslog:
            listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
            idle_timeout: 60s
            label_structured_data: yes
            labels:
              job: firewall
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: host
            - source_labels: ['__syslog_message_hostname']
              target_label: hostname
            - source_labels: ['__syslog_message_severity']
              target_label: 'level'
            - source_labels: ['__syslog_message_severity']
              target_label: 'severity'
            - source_labels: ['__syslog_message_facility']
              target_label: 'facility'
            - source_labels: ['__syslog_message_app_name']
              target_label: 'application'
            - source_labels: ['__syslog_connection_hostname']
              target_label: 'connection_hostname'
          pipeline_stages:
            - match:
                selector: '{host="OPNsense.local"}'
                stages:
                  - regex:
                      expression: '^(?P<rule_number>[\d]+),(?P<sub_rule_number>[\d]*),(?P<anchor>[\d]*),(?P<tracker>[\d]*),(?P<interface>[\w\d]*),(?P<reason>[\w]*),(?P<action>[\w]*),(?P<direction>[\w]*),(?P<ip_version>[\d]*),[x\da-f]*,[x\da-f]*,(?P<packet_ttl>[\d]*),(?P<packet_id>[\d]*),(?P<fragment_offset>[\w]*),(?P<ip_flags>.*?),(?P<protocol_id>[\d]*),(?P<protocol_name>[\w]*),(?P<source_port>[\d]*),(?P<source_ip>[\d.]*),(?P<dest_ip>[\d.]*),(?P<dest_port>[\d]*),'
                  - labels:
                      interface:
                      action:
                      direction:
                      protocol_name:
                      source_ip:
                      source_port:
                      dest_ip:
                      dest_port:

  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 514
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.42.151

  # # Mount journal directory into promtail pods
  # extraVolumes:
  #   - name: journal
  #     hostPath:
  #       path: /var/log/journal

  # extraVolumeMounts:
  #   - name: journal
  #     mountPath: /var/log/journal
  #     readOnly: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
  # readinessProbe:
  #   successThreshold: 1
  #   timeoutSeconds: 1
  # resources:
  #   requests:
  #     cpu: 50m
  #     memory: 48Mi
  #   limits:
  #     cpu: 800m
  #     memory: 96Mi
