global:
  domainName: heimdall.framsburg.ch

heimdall:
  env:
    TZ: Europe/Zurich
  image:
    tag: 2.4.10
  persistence:
    config:
      enabled: true
      type: pvc
      size: 10Gi
      retain: true
      nameOverride: heimdall-config
  # podSecurityContext:
  #   runAsUser: 568
  #   runAsGroup: 568
  #   fsGroup: 568
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: ""
              pathType: ImplementationSpecific
              service:
                name: heimdall
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
