jellyfin:
  ingress:
    main:
      enabled: true
      hosts:
        - host: jellyfin.framsburg.ch
          paths:
            - path: /
              pathType: Prefix
              service:
                name: jellyfin

