jellyfin:
  persistence:
    config:
      enabled: true
    media:
      enabled: true
      type: pvc
      existingClaim: media
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: jellyfin.framsburg.ch
          paths:
            - path: /
              pathType: Prefix
              service:
                name: jellyfin
      tls:
        - hosts: [jellyfin.framsburg.ch]
          secretName: jellyfin-framsburg-ch-tls
