longhorn:
  persistence:
    defaultClassReplicaCount: 2
    backupTargetName: default
  defaultSettings:
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    replicaAutoBalance: disabled # best-effort
    defaultReplicaCount: 2
    createDefaultDiskLabeledNodes: true
    defaultLonghornStaticStorageClass: longhorn
  defaultBackupStore:
    backupTarget: 's3://longhorn@us-east-1/backups'
    backupTargetCredentialSecret: minio2-secret

  metrics:
    serviceMonitor:
      enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-svc-longhorn-headers@kubernetescrd,authentik-authentik@kubernetescrd
    host: longhorn.framsburg.ch
    tls: true
    tlsSecret: longhorn-framsburg-ch-tls
