global:
  domainName: authentik.framsburg.ch

authentik:
  authentik:
    secret_key: dontjudgemethisisjustfortesting    # TODO
    postgresql:
      password: &postgresql_password IKnowThisIsNotASecurePasswordJust4Testing    # TODO

  ingress:
    enabled: true
    # ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: 'authentik.framsburg.ch'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: 'authentik-framsburg-ch-tls'
        hosts: ['authentik.framsburg.ch']

  postgresql:
    enabled: false
    postgresqlPassword: *postgresql_password
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
  redis:
    enabled: false
    image:
      repository: redis
      tag: 6.2.6-apline
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi

postgres:
  userDatabase:
    name: "authentik"
    user: "authentik"
    password: *postgresql_password
  storage:
    className: longhorn
    requestedSize: 10Gi
redis:
  storage:
    className: longhorn
    requestedSize: 10Gi
