global:
  domainName: authentik.framsburg.ch

authentik:
  authentik:
    secret_key: dontjudgemethisisjustfortesting    # TODO
    postgresql:
      password: &postgresql_password IKnowThisIsNotASecurePasswordJust4Testing    # TODO

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: '{{ .Values.global.domainName }}'
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
        hosts: ['{{ .Values.global.domainName }}']

  postgresql:
    enabled: true
    postgresqlPassword: *postgresql_password
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
  redis:
    enabled: true
    image:
      repository: redis
      tag: 6.2.6-apline
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
