---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: weblate-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weblate-secrets
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/data/framsburg/weblate
        property: admin-password
    - secretKey: admin-user
      remoteRef:
        key: secret/data/framsburg/weblate
        property: admin-user
    - secretKey: email-password
      remoteRef:
        key: secret/data/framsburg/weblate
        property: email-password
    - secretKey: email-user
      remoteRef:
        key: secret/data/framsburg/weblate
        property: email-user
    - secretKey: redis-password
      remoteRef:
        key: secret/data/framsburg/weblate
        property: redis-password
    - secretKey: postgresql-user
      remoteRef:
        key: secret/data/framsburg/weblate
        property: postgresql-user
    - secretKey: postgresql-password
      remoteRef:
        key: secret/data/framsburg/weblate
        property: postgresql-password
