loki:


  loki:
#    commonConfig:
#      replication_factor: 1


    schemaConfig:
      configs:
        - from: "2025-07-07"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage:
      type: 's3'
      bucketNames:
        chunks: 'loki-chunks'
        ruler: 'loki-ruler'
        admin: 'loki-admin'
      s3:
        endpoint: 'minio2.framsburg.net'
        accessKeyId: "${GRAFANA_LOKI_S3_ACCESKEYID}"
        secretAccessKey: "${GRAFANA_LOKI_S3_SECRETACCESSKEY}"

  deploymentMode: SimpleScalable

  backend:
    replicas: 2
    extraArgs:
      - '-config.expand-env=true'
    extraEnv:
      - name: GRAFANA_LOKI_S3_ACCESKEYID
        valueFrom:
          secretKeyRef:
            name: minio-access
            key: grafana-loki-s3-accessKeyId
      - name: GRAFANA_LOKI_S3_SECRETACCESSKEY
        valueFrom:
          secretKeyRef:
            name: minio-access
            key: grafana-loki-s3-secretAccessKey
  read:
    replicas: 2
  write:
    replicas: 3 # To ensure data durability with replication

  # Enable minio for storage
  minio:
    enabled: false

  gateway:
    service:
      type: LoadBalancer
