loki:
  # fullnameOverride: loki
  # persistence:
  #   enabled: true
  #   size: 20Gi
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1
  monitoring:
    rules:
      enabled: false