loki:
  # fullnameOverride: loki
  # persistence:
  #   enabled: true
  #   size: 20Gi
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'

  tableManager:
    enabled: true
    retention_deletes_enabled: true
    retention_period: 72h

  singleBinary:
    replicas: 1
    nodeSelector:
      kubernetes.io/arch: amd64
  
  gateway:
    nodeSelector:
      kubernetes.io/arch: amd64
  
  monitoring:
    rules:
      enabled: false
