---
democratic-csi:
  controller:
    driver:
      image:
        tag: next
  csiDriver:
    name: "nfs"
  storageClasses:
    - name: truenas-nfs
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
        - noatime
        - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
  volumeSnapshotClasses:
    - name: nfs
      parameters:
        detachedSnapshots: "true"
  driver:
    config:
      driver: freenas-api-nfs
      instance_id:
      httpConnection:
        apiVersion: 2
        protocol: http
        host: 192.168.42.210
        port: 80
        apiKey: 1-CzF9laWI1ubuqRk7aAzyvNuLlW8QBri4XBibVLWOMJDULmmr7Pbr9yvf6HPENmRN
        allowInsecure: true
      zfs:
        datasetParentName: bigone/k8s/nfs/v
        detachedSnapshotsDatasetParentName: bigone/k8s/nfs/s
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        datasetPermissionsUser: 0
        datasetPermissionsGroup: 0
      nfs:
        shareHost: 192.168.42.210
        shareAlldirs: false
        shareAllowedHosts: [ ]
        shareAllowedNetworks: [ ]
        shareMaprootUser: root
        shareMaprootGroup: root
        shareMapallUser: ""
        shareMapallGroup: ""
