---
democratic-csi:
  controller:
    driver:
      image:
        tag: next
      logLevel: warn
  csiDriver:
    name: "nfs"
  storageClasses:
    - name: truenas-nfs
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
        - noatime
        - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
  volumeSnapshotClasses:
    - name: nfs
      parameters:
        detachedSnapshots: "true"
  driver:
    existingConfigSecret: driver-config-file-secret
    config:
      driver: freenas-api-nfs

  node:
    driver:
      logLevel: warn
