apiVersion: v1
kind: Service
metadata:
  name: rails-demo
  labels:
    {{- include "rails-demo.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "rails-demo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
