global:
  domainName: firefly.framsburg.ch

firefly:
  controller:
    enabled: true
  image:
    tag: "version-6.0.11"
  env:
    TZ: Europe/Zurich

  importer:
    enabled: true
    image:
      tag: "version-1.2.2"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: performance
                  operator: In
                  values:
                    - medium
    specs:
      - accessToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzNmOWYxNDZkZjhhZDNmMTUzYzJjMzE4MmYyZDRjZDM2MDhhZmQ1MTRiNzIxMGRhYjUxZGYxNjE1ZTFlZTMwOGJmY2MzZjMyZmY4NDhhNDMiLCJpYXQiOjE2ODc5NTYyMjEuMDU0NDYxLCJuYmYiOjE2ODc5NTYyMjEuMDU0NDY1LCJleHAiOjE3MTk1Nzg2MjEuMDM2NDgxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.swOiisaJJ3ojrjFxNxk3bLhz927sgO9GvU1fSxbDG7ymGVhE1XmhbCbwDIHsQboIPl7S3GcAVtNAmIqlhX4mZOEoTP8F3qjlJqH3FIPFl5FGWl6MHY8XOE6X-72_bn70cbN9rhAoSe-yFSwSHyWzST7jBrDRlgbl_lX09-UKzJXbV3HI4MLazG-xCKdX7SkP4IjUixG5LY0ksGQ9NwwNddQSu2VXvvt2BFdmUKrpuowCmHh2YXede7eiolpSiKFfc9kNtpTiJHyMvWAlEIzXmuu_Dl82WRbQfsgtWQ4Nyjhew72xRZkfsViJo3y2bSMpde1NuR1WHXPrCiU6B3knzWydHTbCQ9qy4fh-dS3Sz2FMpiYGq4yw8Mg-kPpPbxIOjCtDCvIsGdVVGHnWFjwtZRgoaQqLr5wwJVll1SYwOJN9WhpERcneSU0i3yeg0jin0dB0-96GPx-x2rDJRnxgWQnK4uq_5aosrO4oEwX7yE58Bz3NClCILy9W4SrFvRCsRs1s3tfN3WaA0aWNvYXu43yYBCpc53K6h9qq9DYqTYWP_j-suOJ35SqoOXMZLGXtJUSR_c4uTn3yw-Mg0VWSFXX5NylzD5kvkyAsiQ-rb7NOWwlXyD9bowkOEg-S2LEIx7sc0-z3Tz8UFQSHGLXhVag9Tx6iKC4mwd5voMWjJHo"
        importerName: "default-importer"
        port: 8080
        replicaCount: 1

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: performance
                operator: In
                values:
                  - medium

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
