uptime-kuma:
  persistence:
    data:
      enabled: true
      type: pvc
      size: 10Gi
      accessMode: ReadWriteOnce
  # podSecurityContext:
  #   runAsUser: 568
  #   runAsGroup: 568
  #   fsGroup: 568
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: kuma.framsburg.ch
          paths:
            - path: /
              pathType: Prefix
              service:
                name: uptime-kuma
      tls:
        - hosts: [kuma.framsburg.ch]
          secretName: kuma-framsburg-ch-tls
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 0.5
      memory: 1024Mi
