apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-defrag-job
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcd-defrag-container
            image: quay.io/coreos/etcd:v3.5.6
            command: ["etcd", "defrag"]
          restartPolicy: OnFailure
      backoffLimit: 4
