global:
    domainName: kuma.framsburg.ch

uptime-kuma:
  env:
    TZ: Europe/Zurich
  persistence:
    data:
      enabled: true
      type: pvc
      size: 10Gi
      accessMode: ReadWriteOnce
  # podSecurityContext:
  #   runAsUser: 568
  #   runAsGroup: 568
  #   fsGroup: 568
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths: 
            - path: /
              pathType: Prefix
              service:
                name: uptime-kuma
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
    external:
      enabled: true
      ingressClassName: traefik-external
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths: 
            - path: /
              pathType: Prefix
              service:
                name: uptime-kuma
      tls:
        - hosts: ['{{ .Values.global.domainName }}']
          secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls-external'
  resources:
    requests:
      cpu: 10m
      memory: 56Mi
    limits:
      cpu: 100m
      memory: 128Mi
