---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "allowPostUpgradeCommandTemplating": true,
      "allowedPostUpgradeCommands": ["^.*$", "^sed -i", "^cd "],
      "autodiscover": true,
      "autodiscoverFilter": ["mikevader/*"],
      "requireConfig": "required",
      "hostRules": [
        {
          "hostType": "docker",
          "matchHost": "https://ghcr.io",
          "username": "mikevader",
          "password": "{{ secrets.GITHUB_TOKEN}}"
        },
        {
          "hostType": "docker",
          "username": "baloisemichaelmuehlebach",
          "password": "{{ secrets.DOCKERHUB_PASSWORD }}"
        }
      ],
      "onboardingCommitMessage": "",
      "onboardingConfig": {"$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["local>mikevader/renovate-config"]},
      "onboardingConfigFileName": ".github/renovate.json5"
    }
