---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": ["mikevader/charts","mikevader/images","mikevader/k3s-cluster-infra-apps"],
      "dryRun" : "true"
    }
