---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "allowPostUpgradeCommandTemplating": true,
      "allowedPostUpgradeCommands": ["^.*$", "^sed -i", "^cd "],
      "autodiscover": true,
      "autodiscoverFilter": ["mikevader/*"],
      "requireConfig": "required",
      "hostRules": [
        {
          "hostType": "docker",
          "matchHost": "https://ghcr.io/mikevader",
          "username": "mikevader",
          "password": "{{ secrets.GITHUB_TOKEN}}"
        }
      ],
      "onboardingCommitMessage": "",
      "onboardingConfig": {"$schema": "https://docs.renovatebot.com/renovate-schema.json", "extends": ["mikevader/renovate-config"]},
      "onboardingConfigFileName": ".github/renovate.json5"
    }
