---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "allowPostUpgradeCommandTemplating": true,
      "allowedPostUpgradeCommands": ["^.*$", "^sed -i", "^cd "],
      "repositories": [
        "mikevader/container-images",
        "mikevader/charts",
        "mikevader/k3s-cluster-infra-apps",
        "mikevader/dm-workshop"
      ],
      "hostRules": [
        {
          "hostType": "docker",
          "matchHost": "https://ghcr.io/mikevader",
          "username": "mikevader",
          "password": "{{ secrets.GITHUB_TOKEN}}"
        }
      ]
    }
