---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '*/30 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - image: renovate/renovate:37.131.0
              name: renovate-bot
              env: # For illustration purposes, please use secrets.
                - name: RENOVATE_PLATFORM
                  value: 'github'
                - name: RENOVATE_AUTODISCOVER
                  value: 'true'
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: info

                # - name: RENOVATE_ENDPOINT
                #   value: 'https://github.company.com/api/v3'
                - name: RENOVATE_GIT_AUTHOR
                  value: 'Renovate Bot <bot@renovateapp.com>'

                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secret
                      key: github-token
                - name: GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secret
                      key: github-token
                - name: GITHUB_TOKEN_BASE64
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secret
                      key: github-token-base64

                - name: RENOVATE_SECRETS
                  value: "{\"GITHUB_TOKEN\":\"$(GITHUB_TOKEN_BASE64)\"}"
                - name: DOCKER_HUB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secret
                      key: dockerhub-password

              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
