---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: renovate
  labels:
    app.kubernetes.io/part-of: renovate
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: renovate
    meta.helm.sh/release-namespace: renovate
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: renovate-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: renovate
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: renovate
          meta.helm.sh/release-namespace: renovate
  data:
    - secretKey: github-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/framsburg/renovate/github
        property: token
    - secretKey: github-token-base64
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/framsburg/renovate/github
        property: token_base64
    - secretKey: github-token-finegrained
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/framsburg/renovate/github
        property: token-finegrained
