promtail:
  fullnameOverride: promtail
  serviceMonitor:
    enabled: true
  config:
    #serverPort: 3100
    lokiAddress: http://loki.loki.svc:3100/loki/api/v1/push
    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: journal
          journal:
            path: /var/log/journal
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels:
                - '__journal__systemd_unit'
              target_label: 'unit'
            - source_labels:
                - '__journal__hostname'
              target_label: 'hostname'

        # Add an additional scrape config for syslog
        - job_name: firewall
          syslog:
            listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
            idle_timeout: 60s
            label_structured_data: yes
            labels:
              job: firewall
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: hostname
            - source_labels: ['__syslog_message_severity']
              target_label: 'severity'
            - source_labels: ['__syslog_message_facility']
              target_label: 'facility'
            - source_labels: ['__syslog_message_app_name']
              target_label: 'appname'

  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 514
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.42.151

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 100m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 96Mi
