promtail:
  fullnameOverride: promtail
  serviceMonitor:
    enabled: true
  config:
    #serverPort: 3100
    clients:
      - url: http://loki.loki.svc:3100/loki/api/v1/push

    limit_config:
      readline_rate: 1000
      readline_burst: 2000
      readline_rate_enabled: true

    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: firewall
          syslog:
            listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
            idle_timeout: 60s
            label_structured_data: yes
            labels:
              job: firewall
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: hostname
            - source_labels: ['__syslog_message_severity']
              target_label: 'severity'
            - source_labels: ['__syslog_message_facility']
              target_label: 'facility'
            - source_labels: ['__syslog_message_app_name']
              target_label: 'appname'

  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 514
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.42.151

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
  readinessProbe:
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    requests:
      cpu: 50m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 96Mi
