---
gitops:
  repo: https://github.com/mikevader/k3s-cluster-infra-apps.git
  revision: master
  app_roots:
#    - name: cluster-test
#      autosync_enabled: false
#    - name: cluster-init
#      autosync_enabled: true
#    - name: cluster-critical
#      autosync_enabled: true
#    - name: cluster-platform
#      autosync_enabled: true
#    - name: cluster-apps
#      autosync_enabled: true
