global:
  domainName: samba.framsburg.ch

samba:
  env:
    TZ: Europe/Zurich
    SAMBA_HOSTS_ALLOW: 127.0.0.1/32 192.168.42.0/24
    PERMISSIONS: 
    USERID: 568
    GROUPID: 568

  configmap:
    config:
      enabled: true
      data:
        config.yml: |
          auth:
            - user: foo
              group: foo
              uid: 568
              gid: 568
              password: bar

          global:
            - "force user = foo"
            - "force group = foo"
            - "smb ports = 4445"
            - "create mask = 0666"
            - "force create mode = 0666"
            - "directory mask = 0777"
            - "force directory mode = 0777"
            - "min protocol = SMB2"
            - "vfs objects = fruit streams_xattr recycle"
            - "fruit:metadata = stream"
            - "fruit:model = MacSamba"
            - "fruit:posix_rename = yes"
            - "fruit:veto_appledouble = no"
            - "fruit:wipe_intentionally_left_blank_rfork = yes"
            - "fruit:delete_empty_adfiles = yes"
            - "fruit:nfs_aces = no"
            - "veto files = /._*/.DS_Store/"
            - "delete veto files = yes"
            - "spotlight = no"
            - "fruit:time machine = yes"

          share:
            - name: audiobooks
              path: /mnt/media/audiobooks
              browsable: yes
              readonly: no
              writable: yes
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
              hidefiles: /_*/
              spotlight: no

            - name: movies
              path: /mnt/media/movies
              browsable: yes
              readonly: no
              writable: yes
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
              hidefiles: /_*/

            - name: tv
              path: /mnt/media/tv
              browsable: yes
              readonly: no
              writable: yes
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
              hidefiles: /_*/

  persistence:
    audiobooks:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-audiobooks
      mountPath: /mnt/media/audiobooks

    movies:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies
      mountPath: /mnt/media/movies

    tv:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv
      mountPath: /mnt/media/tv

  # podSecurityContext:
  #   runAsUser: 568
  #   runAsGroup: 568
  #   fsGroup: 568
  service:
    main:
      ports:
        tcp:
          enabled: true
          protocol: TCP
          port: 4445
  # ingress:
  #   main:
  #     enabled: true
  #     annotations:
  #       # cert-manager.io/cluster-issuer: letsencrypt-prod
  #       traefik.ingress.kubernetes.io/router.entrypoints: smb
  #     ingressClassName: traefik
  #     hosts:
  #       - host: '{{ .Values.global.domainName }}'
  #         paths:
  #           - path: ""
  #             pathType: ImplementationSpecific
  #             service:
  #               name: samba
  #               port:
  #                 number: 445
      # tls:
      #   - hosts: ['{{ .Values.global.domainName }}']
      #     secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
