global:
  domainName: samba.framsburg.ch

samba:
  env:
    TZ: Europe/Zurich
    SAMBA_HOSTS_ALLOW: 127.0.0.1/32 192.168.42.0/24
    PERMISSIONS: 
    USERID: 568
    GROUPID: 568

  configmap:
    config:
      enabled: true
      data:
        config.yml: |
          auth:
            - user: foo
              group: foo
              uid: 568
              gid: 568
              password: bar

          global:
            - "force user = foo"
            - "force group = foo"
            - "min protocol = SMB2"
            - "ea support = yes"
            - "vfs objects = fruit streams_xattr"
            - "fruit:metadata = stream"
            - "fruit:resource = stream"
            - "fruit:model = MacSamba"
            - "fruit:veto_appledouble = no"
            - "fruit:posix_rename = yes"
            - "fruit:zero_file_id = yes"
            - "fruit:wipe_intentionally_left_blank_rfork = yes"
            - "fruit:delete_empty_adfiles = yes"

          share:
            - name: audiobooks
              path: /mnt/media/audiobooks
              browsable: yes
              readonly: no
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
              hidefiles: /_*/

            - name: movies
              path: /mnt/media/movies
              browsable: yes
              readonly: no
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
              hidefiles: /_*/

            - name: tv
              path: /mnt/media/tv
              browsable: yes
              readonly: no
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
              hidefiles: /_*/

  persistence:
    audiobooks:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-audiobooks
      mountPath: /mnt/media/audiobooks

    movies:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-movies
      mountPath: /mnt/media/movies

    tv:
      enabled: true
      type: pvc
      retain: true
      storageClass: "-"
      existingClaim: plex-tv
      mountPath: /mnt/media/tv

  # podSecurityContext:
  #   runAsUser: 568
  #   runAsGroup: 568
  #   fsGroup: 568

  ingress:
    main:
      enabled: true
      annotations:
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: smb
      ingressClassName: traefik
      hosts:
        - host: '{{ .Values.global.domainName }}'
          paths:
            - path: ""
              pathType: ImplementationSpecific
              service:
                name: samba
      # tls:
      #   - hosts: ['{{ .Values.global.domainName }}']
      #     secretName: '{{ .Values.global.domainName | replace "." "-" }}-tls'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
