apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: apps-cluster-test
spec:
  enableLogicalBackup: true
  databases:
    fireflydb: firefly
  numberOfInstances: 2
  postgresql:
    version: '15'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    firefly: []
  volume:
    size: 10Gi
