---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring-stack
data:
  oidc-id: dmF1bHQ6c2VjcmV0L2RhdGEvZnJhbXNidXJnL2dyYWZhbmEvb2lkYyNjbGllbnQtaWQ=
  oidc-secret: dmF1bHQ6c2VjcmV0L2RhdGEvZnJhbXNidXJnL2dyYWZhbmEvb2lkYyNjbGllbnQtc2VjcmV0
type: Opaque
