---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring-stack
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc:8200"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-role: "grafana"
    vault.security.banzaicloud.io/vault-skip-verify: "true" 
data:
  oidc-id: dmF1bHQ6c2VjcmV0L2RhdGEvZnJhbXNidXJnL2dyYWZhbmEvb2lkYyNjbGllbnQtaWQ=
  oidc-secret: dmF1bHQ6c2VjcmV0L2RhdGEvZnJhbXNidXJnL2dyYWZhbmEvb2lkYyNjbGllbnQtc2VjcmV0
type: Opaque
