apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: rails-demo-sla-2
  namespace: monitoring-stack
spec:
  service: "rails-demo"
  labels:
    owner: "myteam"
    repo: "myorg/myservice"
    tier: "2"
  slos:
    - name: "requests-availability-2"
      objective: 99.5
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        events:
          errorQuery: sum(rate(ruby_http_requests_total{code=~"(5..|429)"}[{{`{{ ".window" }}`}}]))
          totalQuery: sum(rate(ruby_http_requests_total[{{`{{ ".window" }}`}}])) 
      alerting:
        pageAlert:
          disable: true
        ticketAlert:
          disable: true
