apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: enabled
  RAILS_SERVE_STATIC_FILES: enabled
#  DATABASE_URL: postgresql://example.com/mydb
#  REDIS_URL: redis://redis.default.svc.cluster.local:6379/