apiVersion: v2
name: authentik
version: 0.0.0
dependencies:
  - name: authentik
    version: 2025.8.4
    repository: https://charts.goauthentik.io

  - name: redis
    version: 2.1.3
    repository: https://groundhog2k.github.io/helm-charts

  - name: postgres
    version: 1.4.8
    repository: https://groundhog2k.github.io/helm-charts
    alias: postgresql16
